name: Scala CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4.1.1
            -   name: Set up JDK
                uses: actions/setup-java@v4.0.0
                with:
                    java-version: '21'
                    distribution: 'temurin'
            -   name: Quality Check
                run: ./sbtx clean coverage test scalafmtCheckAll "scalafixAll --check" coverageReport
            -   name: Upload coverage to Codecov
                uses: codecov/codecov-action@v4
                with:
                    directory: ./target/scala-2.13/coverage-report/
                    fail_ci_if_error: true
                    files: ./cobertura.xml
                    name: scala-kata-base
                    token: ${{ secrets.CODECOV_TOKEN }}
                    slug: rstraub/scala-kata-base
