name: Scala CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4.1.1
            -   name: Set up JDK
                uses: actions/setup-java@v4.0.0
                with:
                    java-version: '21'
                    distribution: 'temurin'
            -   name: Quality Check
                run: ./sbtx clean coverage test scalafmtCheckAll "scalafixAll --check" coverageReport
            - name: Code Coverage Report
              uses: irongut/CodeCoverageSummary@v1.3.0
              with:
                filename: target/scala-2.13/coverage-report/cobertura.xml
                badge: true
                format: markdown
